version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment_test
    ports:
      - '5433:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://payment:payment@db:5432/payment_db
      JWT_SECRET: changeme-jwt
      JWT_REFRESH_SECRET: changeme-refresh
      CARD_ENCRYPTION_KEY: 0000000000000000000000000000000000000000000000000000000000000001
      PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
